language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - export PYTHONPATH=$(pwd):$PYTHONPATH
script: coverage run --source=. --omit=tests/*,*__init__.py,setup.py -m unittest discover
after_success:
  coveralls