language: python
python:
  - "2.7"
  - "3.5"
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script: coverage run --omit tests/* -m unittest discover tests
after_success:
  coveralls